### ISSUE TITLE
starting dev environment

### ISSUE THREAD

**Issue by tolgraven** [WorksHub/client#16]
Dev env things you might consider, maybe not true issues.

- Lacking info about getting nrepl working with piggyback, and I couldn't get it to up either `lein repl -> figwheel` nor adding nrepl-port to lein figwheel.
Or rather, it connects, but then get transport nil. Anything obvious I missed?

- Would definitely help having more dummy data in API system.
(eg. checkbox on-click issue but no part clickable as all disabled)

- Seems partly expecting site at functional.localdomain.
Domains hardcoded, as is ws/figwheel port etc, maybe move to env?
Figwheel got stuck caching 3450 port when I attempted that, until lein clean.
Not sure what could be done about latter. Just thinking people who
might contribute might usually keep 3449 real busy and flexibility is good :)

- x-workshub-version xhrio header refused.

Very cool you've got this whole thing up here, certainly dwarfs most "look at this real world project!!" stuff in scale.

**Comment by acron0** [comment]
```
Lacking info about getting nrepl working with piggyback, and I couldn't get it to up either lein repl -> figwheel nor adding nrepl-port to lein figwheel.
Or rather, it connects, but then get transport nil. Anything obvious I missed?
```
We regularly check the `lein figwheel` command so I am surprised you're having trouble. Are there error messages you can show us?

**Comment by tolgraven** [comment]
The repl works fine, I mean piggyback + nrepl (as with `lein repl`) to connect editor. 20s recompiles get very tricky with a workflow mainly consisting of manically mashing keys at all times, evaling. To me that's clojure. I think it's called gamification?
But makes, uh ok, if answer is "unsupported", I haven't started fiddling with it yet just wanted to check first.

**Comment by acron0** [comment]
Yeah, this setup is fairly rudimentary. Feel free to add nREPL support (port etc). There are plenty of guides on how to do this. If you just want quick file reloading then run `lein figwheel` in a separate terminal.
