### ISSUE TITLE
Trying to setup the WorksHub client

### ISSUE THREAD

**Issue by Alex-Bakic** [WorksHub/client#4]
Hey there, I'm in the middle of writing a reagent and re-frame guide and the project I wanted to accompany it was this frontend. I've never grokked a frontend as massive , so I have a few questions about setting it all up.

The first error I ran into was with the `cljsjs` packages. When I ran `npm install; lein figwheel` everything went through with no problems , but then I got the error:

    No such namespace: cljsjs.moment, could not locate cljsjs/moment.cljs
    
I figured it was just that I needed to run lein deps and pull in this dependency; I tried this to no avail but after specifiying it `project.clj` I got it working.

So after adding 

    [cljsjs/moment "2.24.0-0"]
    
And trying `lein deps; lein figwheel` I didn't run into that error , but then another in the form of:

    Failed to compile build :client from ["client/env/dev" "client/src" "common/src" "common-pages/src"] in 33.202 seconds.
    ----  Could not Analyze  common/src/wh/components/info_icon.cljc  ----

    No such namespace: cljsjs.react-tooltip, could not locate cljsjs/react_tooltip.cljs, cljsjs/react_tooltip.cljc, or JavaScript source providing "cljsjs.react-tooltip" (Please check that namespaces with dashes use underscores in the ClojureScript file name) 

    ----  Analysis Error : Please see common/src/wh/components/info_icon.cljc  ----
    Figwheel: initial compile failed - outputting temporary helper application to target/resources/public/js/wh.js

So it was another namespace issue , and after trying the same solution to the above I no longer got namespace errors. 

I actually did get a successful compilation , however rebel-readline wasn't evaluating and when I would visit the http://localhost:3449 address it shows 

    Cannot open <nil> as a Reader.
    java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
    at clojure.java.io$fn__11490.invokeStatic (io.clj:288)
    clojure.java.io/fn (io.clj:288)
    clojure.java.io$fn__11392$G__11368__11399.invoke (io.clj:69)
    clojure.java.io$reader.invokeStatic (io.clj:102)
    clojure.java.io$reader.doInvoke (io.clj:86)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$slurp.invokeStatic (core.clj:6942)
    clojure.core$slurp.doInvoke (core.clj:6942)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    wh.server$load_public_js.invokeStatic (server.clj:21)
    wh.server$load_public_js.invoke (server.clj:19)
    wh.server$fn__28912$fn__28915$fn__28917.invoke (server.clj:30)
    clojure.core$map$fn__5851.invoke (core.clj:2753)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.RT.seq (RT.java:531)
    clojure.core$seq__5387.invokeStatic (core.clj:137)
    clojure.core/seq (core.clj:137)
    net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___25225.invoke (enlive_html.clj:228)
    net.cgrand.enlive_html$flatten_nodes_coll$flat__25231$fn__25232.invoke (enlive_html.clj:233)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.RT.seq (RT.java:531)
    clojure.core$seq__5387.invokeStatic (core.clj:137)
    clojure.core$dorun.invokeStatic (core.clj:3133)
    clojure.core$doall.invokeStatic (core.clj:3148)
    clojure.core$doall.invoke (core.clj:3148)
    wh.server$fn__28912$fn__28915.invoke (server.clj:24)
    clojure.core$comp$fn__5792.invoke (core.clj:2569)
    wh.server$index_handler.invokeStatic (server.clj:54)
    wh.server$index_handler.invoke (server.clj:53)
    bidi.ring$eval21450$fn__21451.invoke (ring.cljc:25)
    bidi.ring$eval21429$fn__21430$G__21420__21439.invoke (ring.cljc:16)
    bidi.ring$make_handler$fn__21459.invoke (ring.cljc:43)
    ring.middleware.resource$wrap_resource$fn__21411.invoke (resource.clj:37)
    ring.middleware.content_type$wrap_content_type$fn__21183.invoke (content_type.clj:34)
    clojure.lang.Var.invoke (Var.java:384)
    figwheel_sidecar.components.figwheel_server$possible_endpoint$fn__18873.invoke (figwheel_server.clj:225)
    figwheel_sidecar.components.figwheel_server$handle_static_resources$fn__18853.invoke (figwheel_server.clj:198)
    figwheel_sidecar.components.figwheel_server$handle_index$fn__18844.invoke (figwheel_server.clj:183)
    figwheel_sidecar.components.figwheel_server$handle_figwheel_websocket$fn__18867.invoke (figwheel_server.clj:220)
    figwheel_sidecar.components.figwheel_server$wrap_no_cache$fn__18878.invoke (figwheel_server.clj:240)
    co.deps.ring_etag_middleware$wrap_file_etag$fn__18069.invoke (ring_etag_middleware.clj:94)
    ring.middleware.not_modified$wrap_not_modified$fn__18045.invoke (not_modified.clj:53)
    ring.middleware.cors$handle_cors.invokeStatic (cors.clj:171)
    ring.middleware.cors$handle_cors.invoke (cors.clj:160)
    ring.middleware.cors$wrap_cors$fn__18017.invoke (cors.clj:185)
    figwheel_sidecar.components.figwheel_server$log_output_to_figwheel_server_log$fn__18835.invoke (figwheel_server.clj:144)
    org.httpkit.server.HttpHandler.run (RingHandler.java:115)
    java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    java.util.concurrent.FutureTask.run (FutureTask.java:264)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    java.lang.Thread.run (Thread.java:835)

Tracking this back to the client/server/src/wh/server.clj file it shows a section:

    (defn- load-public-js
      []
      (let [files (read-string (slurp (io/resource "publicjs.edn")))]
      (reduce #(str %1 (slurp (io/resource (.getName (clojure.java.io/file %2))))) "" files)))

But I couldn't find a `publicjs.edn` file, so I commented out the templating code that called this fn within `wh-index-template` then it seems to compile , but running `lein-figwheel` and after visiting http://localhost:3449 I got the following: 

    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/clojure/walk.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/spec/gen/alpha.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/clojure/string.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/spec/alpha.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/repl.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/pprint.cljs
    Compiling /home/alex/wh/client/common-pages/src/wh/company/listing/events.cljc to target/resources/public/js/wh/company/listing/events.js
    Reading analysis cache for jar:file:/home/alex/.m2/repository/bidi/bidi/2.1.3/bidi-2.1.3.jar!/bidi/bidi.cljc
    Reading analysis cache for file:/home/alex/wh/client/client/src/pushy/core.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/debug.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/interop.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/impl/util.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/impl/batching.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/clojure/set.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/ratom.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/impl/component.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/impl/template.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/dom.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/reagent/reagent/0.7.0/reagent-0.7.0.jar!/reagent/core.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/interop.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/db.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/loggers.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/utils.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/registrar.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/trace.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/interceptor.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/events.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/subs.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/router.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/fx.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/cofx.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/clojure/data.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/std_interceptors.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/re-frame/re-frame/0.10.5/re-frame-0.10.5.jar!/re_frame/core.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/util.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/paths.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/ansi.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/printer.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/problems.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar!/expound/alpha.cljc
    Reading analysis cache for file:/home/alex/wh/client/client/env/dev/wh/interceptors.cljs
    Reading analysis cache for file:/home/alex/wh/client/client/src/wh/login/github_callback/db.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.0/camel-snake-kebab-0.4.0.jar!/camel_snake_kebab/internals/string_separator.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.0/camel-snake-kebab-0.4.0.jar!/camel_snake_kebab/internals/misc.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.0/camel-snake-kebab-0.4.0.jar!/camel_snake_kebab/internals/alter_name.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.0/camel-snake-kebab-0.4.0.jar!/camel_snake_kebab/core.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/camel-snake-kebab/camel-snake-kebab/0.4.0/camel-snake-kebab-0.4.0.jar!/camel_snake_kebab/extras.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/cases.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/text.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/data.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/util.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/user.cljc
    Reading analysis cache for file:/home/alex/wh/client/client/src/wh/user/db.cljs
    Reading analysis cache for file:/home/alex/wh/client/client/src/wh/db.cljs
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/pages/modules.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/specs/primitives.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/routes.cljc
    Reading analysis cache for file:/home/alex/wh/client/client/src/wh/pages/core.cljs
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/graphql_cache.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/re_frame/subs.cljc
    Reading analysis cache for file:/home/alex/wh/client/client/src/wh/common/fx/google_maps.cljs
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/location.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/env.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/impl/utils.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/reader_types.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/impl/inspect.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/impl/errors.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/impl/commons.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/tools.reader/1.3.0/tools.reader-1.3.0.jar!/cljs/tools/reader/edn.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/reader.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/tagged_literals.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/analyzer.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/analyzer/api.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/metosin/spec-tools/0.8.0/spec-tools-0.8.0.jar!/spec_tools/impl.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/metosin/spec-tools/0.8.0/spec-tools-0.8.0.jar!/spec_tools/form.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/metosin/spec-tools/0.8.0/spec-tools-0.8.0.jar!/spec_tools/parse.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/metosin/spec-tools/0.8.0/spec-tools-0.8.0.jar!/spec_tools/transform.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/longs/bit_count_impl.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/longs.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/doubles.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/rose_tree.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/generators.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/metosin/spec-tools/0.8.0/spec-tools-0.8.0.jar!/spec_tools/core.cljc
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/internal/core.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/core.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/internal/parse.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/internal/unparse.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/format.cljs
    Reading analysis cache for jar:file:/home/alex/.m2/repository/com/andrewmcveigh/cljs-time/0.5.2/cljs-time-0.5.2.jar!/cljs_time/coerce.cljs
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/specs/date.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/specs/tags.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/specs/company.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/specs/location.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/common/url.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/components/icons.cljc
    Reading analysis cache for file:/home/alex/wh/client/common/src/wh/components/tag.cljc
    Reading analysis cache for file:/home/alex/wh/client/common-pages/src/wh/company/profile/db.cljc
    Reading analysis cache for file:/home/alex/wh/client/common-pages/src/wh/company/listing/subs.cljc
    Reading analysis cache for file:/home/alex/wh/client/common-pages/src/wh/company/listing/db.cljc
    Copying file:/home/alex/wh/client/common-pages/src/wh/company/listing/events.cljc to target/resources/public/js/wh/company/listing/events.cljc
    Compiling target/resources/public/js/cljs/loader.cljs to target/resources/public/js/cljs/loader.js

it compiles without any errors, but how do I get the ui shown? At the moment all I see is the debugging tools

I think I'm just being silly but if anyone could point me in the right direction that would be much appreciated :sweat_smile:

**Comment by acron0** [comment]
@Alex-Bakic This should be fixed in https://github.com/WorksHub/client/commit/19242b5b12227fdcb3b30f8f078e6eb484d7dbd1 - pleaqse can you confirm for me?

**Comment by Alex-Bakic** [comment]
Just reinstalled and it went smoothly, no issues :thumbsup:
