### ISSUE TITLE
div id="chatbot" height exceeds window height on desktop in turn hiding close button

### ISSUE THREAD

**Issue by jcwii** [WorksHub/client#49]
Hello,

A job application I made today on desktop was met with the chatbot popup which first asked for a cover letter and then upon reply confirmed my submission. I noticed that the chatbot div was set to a height of 500px when @media screen and (min-width: 1008px) as shown in the screenshot below:

![applied-chatbotDiv](https://user-images.githubusercontent.com/52218669/101203316-7988a980-3638-11eb-91dd-b599ca39392c.JPG)

As shown, the close icon ("X") on the chatbot div was mostly hidden and thus not very perceptible because of the div's height. In Chrome with DevTools I set the max-height of div id="chatbot" to 80vh which in turn showed the close icon in full. Adding this attribute/value pair would prevent the top of this div from flowing off-screen in other instances for users with browser window heights less than ~485px (500px height - 15px bottom), example shown in screenshot below:

![applied-chatbotDiv-edit](https://user-images.githubusercontent.com/52218669/101204096-b3a67b00-3639-11eb-9254-c6fdd9619d74.JPG)

Just for fun (and as shown above) I duplicated the last aside class="animatable codi-container " element inside the chatbot div a few times to ensure that scrolling is preserved with this fix, and indeed it is.

Please let me know if you have any questions. @jonki thank you for your response to the social icon clash that I brought to Nick's attention yesterday, the fix looks great. Have a nice day everyone, beautiful website.

-jcwii

**Comment by acron0** [comment]
@jcwii This is a great issue. Do you fancy turning it into a PR for us?

**Comment by jcwii** [comment]
> @jcwii This is a great issue. Do you fancy turning it into a PR for us?

Thanks! And done!
