### ISSUE TITLE
unexpected click behavior in footer

### ISSUE THREAD

**Issue by jcwii** [WorksHub/client#52]
In some instances the works-hub.com footer experiences unexpected click behavior. Specifically when window width and height are such that only one div class="footer__sitemap__list" is in a flex row (within the div class="footer__sitemap__list__container"), links in this footer__sitemap__list class have onclick hyperlink action outside of their text areas. Here's an example illustrated nicely with DevTools:

![footerAnchorElements](https://user-images.githubusercontent.com/52218669/101843115-8107f100-3b17-11eb-8e2c-0c6d44203e3b.gif)

As shown the a elements (and their hyperlink actions) extend nearly full window width with this div class="footer__sitemap__list" being the only one in its row. Since most browsers handle block divs within flex divs where "flex-wrap: wrap;" similarly, this behavior is likely exhibited across many user devices, as is the case with my phone.

To give hyperlinking action to only the text, simply set the width of these footer anchor elements to fit-content.

Let me know if you'd like a PR. I'm continuing to really enjoy your website, and I'm really looking forward to writing articles for works-hub.com/learn/, thank you to the team for being so responsive.

**Comment by acron0** [comment]
Hi James, thanks yet again! We would definitely appreciate a PR for this. We are hoping to spend more time in the New Year going through and tidying up some of our discrepancies such as this one but you're doing us a huge favour by highlighting and possibly even fixing some of them.

We look forward to your articles!

**Comment by jcwii** [comment]
Hey Antony, the pleasure is all mine. If there's anything I can do in the New Year to help, perhaps site-wide QA, just leave a note. Otherwise similarly I'm very much looking forward to sending articles your way, thanks!
